# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
#            token_id: submit
            field_name: submit

    csrf_protection:
        enabled: true
#        stateless_token_ids:
#            - submit
#            - authenticate
#            - logout
