# fussball.de Test-Controller
fussballde_test:
    path: /fussballde/test
    controller: App\Controller\FussballDeTestController::test
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#api_login:
#    path: /api/login