doctrine_migrations:
    enable_profiler: false
    transactional: false  # Verhindert Transaktionsprobleme
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    organize_migrations: BY_YEAR_AND_MONTH
    storage:
        table_storage:
            table_name: doctrine_migration_versions
