# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true
    profiler:
        collect: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    serializer:
        enabled: true
        default_context:
            max_depth: 3  # oder eine andere Zahl, je nach Bedarf
#        mapping:
#            paths: ['%kernel.project_dir%/config/serialization']
    assets:
        base_path: /uploads

parameters:
    upload_directory: '/mnt/gdrive/uploads'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
