security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        login:
#            pattern: ^/api/login
#            stateless: true
#            json_login:
#                check_path: /api/login
#                username_path: email
#                password_path: password
#                success_handler: lexik_jwt_authentication.handler.authentication_success
#                failure_handler: lexik_jwt_authentication.handler.authentication_failure
#            user_checker: App\Security\UserChecker
#            provider: app_user_provider 

        api:
            pattern: ^/api
            stateless: true
#            entry_point: App\Security\JwtEntryPoint
            jwt: ~

        # kein jwt, kein authenticator
        verify_email:
            pattern: ^/api/verify/email
            stateless: true
            provider: app_user_provider
            security: false

        main:
            stateless: true
            provider: app_user_provider
            jwt: ~
            custom_authenticators:
                - App\Security\GoogleAuthenticator
#            logout:
#                path: /api/logout
#                invalidate_session: true

    role_hierarchy:
        ROLE_GUEST:       []
        ROLE_USER:        [ROLE_GUEST]
        ROLE_SUPPORTER:   [ROLE_USER]
        ROLE_CLUB:        [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPERADMIN:  [ROLE_ADMIN]

    access_control:
    - { path: ^/connect/google, roles: PUBLIC_ACCESS }
    - { path: ^/connect/google/check, roles: PUBLIC_ACCESS }
    - { path: ^/admin,        roles: ROLE_ADMIN }
    - { path: ^/news,         roles: ROLE_USER }
    - { path: ^/api/users,    roles: ROLE_USER }
    - { path: ^/api/messages/unread-count, roles: ROLE_USER }
    - { path: ^/api/messages, roles: ROLE_USER }
    - { path: ^/api/message-groups, roles: ROLE_USER }
    - { path: ^/api/profile,  roles: ROLE_USER }
    - { path: ^/api/players,  roles: ROLE_USER }
    - { path: ^/api/register, roles: PUBLIC_ACCESS }
    - { path: ^/api/login,    roles: PUBLIC_ACCESS }
    - { path: ^/api/verify,   roles: PUBLIC_ACCESS }
    - { path: ^/api,          roles: PUBLIC_ACCESS }
